## A basic GitHub Actions workflow for your Quarkus application.

name: CI build faucet chatbot

on:
  push:
    tags: [ v* ]
    branches: [ main ]
    paths:
    - '**'
    - '.github/workflows/ci-faucet-chatbot.yml'
  workflow_dispatch:

env:
  QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
  QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKER_HUB_PWD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
        
      - name: Build
        run: |
          ./mvnw package -B -Dquarkus.container-image.tag=${GITHUB_REF##*/}
          docker image ls